# Generated by Django 3.2.9 on 2021-11-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutputVideo',
            fields=[
                ('output_id', models.IntegerField(primary_key=True, serialize=False)),
                ('request_id', models.IntegerField()),
                ('video_id', models.IntegerField()),
                ('output_source', models.CharField(max_length=100)),
                ('decoding_key', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'output_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('request_date', models.DateField()),
                ('center_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('child_name', models.CharField(max_length=20)),
                ('request_reason', models.CharField(max_length=200)),
                ('process_state', models.IntegerField()),
                ('check', models.IntegerField()),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.IntegerField(primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
    ]
